# Generated by Django 3.0.3 on 2020-03-01 01:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=70, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/imagenes')),
                ('estado', models.CharField(choices=[('no_publicado', 'No Publicado'), ('publicado', 'Publicado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], max_length=12)),
                ('creado', models.DateField(auto_now_add=True)),
                ('modificado', models.DateField(auto_now=True)),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Estadio')),
            ],
        ),
        migrations.CreateModel(
            name='LocalidadEstadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=25)),
                ('aforo', models.PositiveIntegerField()),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Estadio')),
            ],
            options={
                'verbose_name_plural': 'Localidades Estadio',
                'unique_together': {('localidad', 'estadio')},
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='LocalidadEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(0)])),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.LocalidadEstadio')),
            ],
            options={
                'verbose_name_plural': 'Localidades Evento',
                'unique_together': {('evento', 'localidad')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='localidades',
            field=models.ManyToManyField(through='eventos.LocalidadEvento', to='eventos.LocalidadEstadio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.TipoEvento'),
        ),
    ]
