# Generated by Django 3.0.3 on 2020-02-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='address',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
